version: '3.8'

services:
  app:
    # build: . for using local build
    image: omkar0301/node_js_boilerplate:latest
    ports:
      - '8081:8081'
    env_file:
      - .env.development
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: