version: '3.8'

services:
  app:
    # build: . for using local build
    image: omkar0301/node_js_boilerplate:latest
    ports:
      - '8081:8081'
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo:27017/boilerplate
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: